Alias:   CAP = http://cap.org/eCC
//address for CAP terminology
Alias:   LNC = http://loinc.org
Alias:   SCT = http://snomed.info/sct
Alias:   UCUM = http://unitsofmeasure.org
Alias:   ICD10CM = http://hl7.org/fhir/sid/icd-10-cm
Alias:   ICD10PCS = http://www.cms.gov/Medicare/Coding/ICD10
Alias:   RXN = http://www.nlm.nih.gov/research/umls/rxnorm
Alias:   ICDO3 = http://terminology.hl7.org/CodeSystem/icd-o-3
Alias:   ObsCat = http://terminology.hl7.org/CodeSystem/observation-category
Alias:   ObsStatus = http://hl7.org/fhir/observation-status
Alias:   ObsInt = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
Alias:   $WG = http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
